### ISSUE TITLE
Compatibility with new version "Hogfather"

### ISSUE THREAD

**Issue by csporrer** [Klap-in/dokuwiki-plugin-searchform#6]
Can the plugin be adapted for the latest version "Hogfather" of DokuWiki?
Basically I think the plugin is very good and would be glad if it would be maintained further.

**Comment by Klap-in** [comment]
Good question. I made once a start. It will take some time for I’m done.

**Comment by LMS235** [comment]
Any news? Would like to use the plugin, but we are already on Hogfather

**Comment by Klap-in** [comment]
At the moment I am working on the Indexmenu plugin, but maybe it is worth to have a look into this before..

Are there specific issues?

**Comment by csporrer** [comment]
On the DokuWiki page the plugin is listed as not compatible: https://www.dokuwiki.org/plugin:searchform
I don't know why but this is the reason I opened this issue.  In Github there is one other issue because of PHP7:
https://github.com/Klap-in/dokuwiki-plugin-searchform/issues/3

**Comment by Klap-in** [comment]
Please check the latest update. Is this update fine for you?

**Comment by csporrer** [comment]
Absolutely, thanks for your support!
