### ISSUE TITLE
Exclude Namespace?

### ISSUE THREAD

**Issue by LMS235** [Klap-in/dokuwiki-plugin-searchform#7]
How can i exclude a namespace from search?

Like: `ns:search -ns:nosearch`

**Comment by LMS235** [comment]
**bump**

**Comment by Klap-in** [comment]
I have added the option to use `-ns:excludenamespace`. So you could exclude also namespaces instead searching in a specific namespace. The quicksearch is not yet working (that needs a change in dokuwiki itself).

**Comment by Klap-in** [comment]
@LMS235 could you test this? does this work as expected?

**Comment by LMS235** [comment]
@Klap-in work as expected :) Thank you
