### ISSUE TITLE
Issue with current version of the plugin (pages are not displayed)

### ISSUE THREAD

**Issue by asheenlevrai** [Klap-in/dokuwiki-plugin-searchform#8]
Hi :)

I am currently running DokuWiki Release 2018-04-22c "Greebo" from a Synology NAS. I have been using this setup for several years and everything usually works smoothly.

Recently I updated several plugins via the Extension Manager in the Admin Admin panel, including this plugin (Search Form Plugin).

Since this update, all pages that include {searchform} are no longer displayed (black screen) and tools on the right-hand toolbar are no longer available (buttons not displayed), e.g. edit page, previous version, manage subscriptions, ... 

Disabling the plugin makes the pages to be displayed properly again (although obviously {searchform} is displayed rather than the search field). Re-installing the plugin doesn't fix anything (black screen).

I don't know what I should do. I don't know what other info could be relevant in this case.
Synology NAs runs the following packages: PHP7.2, PHP7.0, PHP5.6. I don't know if this is relevant.

Thank you very much in advance for your help, guidance and advice.
Best,
-a-

**Comment by Klap-in** [comment]
Could you check if the log contains messages?
Please see for more background https://www.dokuwiki.org/faq:blankpage

**Comment by asheenlevrai** [comment]
Thanks :)

I run from a Synology NAS so AFAIK I don't have access to /var (/var/log/...).
I guess I could if I'd SSH into it but I'm not familiar with that kind of things unfortunately (excuse my ignorance).

There are no error_log file anywhere either.

I'll look into [showphperrors](https://www.dokuwiki.org/plugin:showphperrors) (it's not marked as compatible with Greebo) ASAP and report here if I manage to get any useful info from it.

Thanks again :)
Best,
-a-

**Comment by asheenlevrai** [comment]
ShowPhpErrors returns this:

Fatal error: Class 'dokuwiki\Extension\Event' not found in /volume1/web/dokuwiki/lib/plugins/searchform/syntax.php on line 121

**Comment by Klap-in** [comment]
You are using an older version of DokuWiki. The plugin is updated, and uses recent added features, sorry, at time of updating I did not realize it would break backward-compatibility. 
Solution is updating your wiki (probably more and more plugins will have this challenge), or installing an older version of the plugin. e.g. you could try: https://github.com/Klap-in/dokuwiki-plugin-searchform/archive/609fb548c273382d9cc3a2b117aa3c0daf16c735.zip

**Comment by asheenlevrai** [comment]
Thank you :)

I am currently in the process of figuring out the best way to update our wiki and all its plugins.
Some are more problematic than others.

Best,
-a-

**Comment by Klap-in** [comment]
No changes needed.
