### ISSUE TITLE
Error in new Version

### ISSUE THREAD

**Issue by LMS235** [Klap-in/dokuwiki-plugin-searchform#9]
After update to the new version the following is on top of the page:

_Array ( [namespace] => namespace1:namespace2 [excludens] => )_

Pagecode: `{searchform ns=namespace1:namespace2}`

downgrade to the old version, error is gone. can you please check.

**Comment by Klap-in** [comment]
Thanks for mentioning! Here a debug statement is left: https://github.com/Klap-in/dokuwiki-plugin-searchform/blob/a7fead87177332a71e12fc5a64e0b5cec9294162/syntax.php#L78 I will create an update in short term.

**Comment by Klap-in** [comment]
Thanks for your report, I'm sorry for the inconvenience!
